add credential caching; invalidate upon secret change
Testing so far is [a] confirming that existing behavior works, and [b]
manually checking call counts to oath2. This works via:

```
AZURE_LOG_LEVEL=verbose <run-test> 2>&1 | tee test.log
grep -c test.log
```

Specifically, spn_auth.test drops from 3 -> 1 oauth2 calls, and across
the entire test suite (non-slow), oauth2 calls drop from 260 -> 26. So
it's definitely working within context.

Additionally tested credential invalidations when SECRET replaced,
confirmed that the SECRET forces the minting of a new token.

diff --git a/scripts/env_azurite b/scripts/env_azurite
--- a/scripts/env_azurite
+++ b/scripts/env_azurite
@@ -24,12 +24,12 @@ export TEMP_DIR="$AZ_TEMPDIR"
 
 # for compatibility, accept --az arg, and fail on --abfss
 [[ -n "$1" && "$1" = "--abfss" ]] && {
-	echo "run_azurite can only operate in --az mode, aborting." >&2
-	exit
+  echo "run_azurite can only operate in --az mode, aborting." >&2
+  exit
 }
 [[ -n "$1" && "$1" = "--az" ]] && {
-	# NOOP
-	shift
+  # NOOP
+  shift
 }
 
-exec "$@"
+exec env "$@"
